### ISSUE TITLE
Set API Authentication

### ISSUE THREAD

**Issue by bobvanluijt** [weaviate/weaviate-swagger#29]
Set:

```
securityDefinitions:
  apiKey:
    type: apiKey
    in: header
    name: X-API-KEY
security:
  - key: []
```
